### ISSUE TITLE
Podcast track returning null

### ISSUE THREAD

**Issue by niveKKumar** [spotify-api/spotify-api.js#147] opened 2022-06-28 10:26 UTC
# Bug Report

## What i expected:

```
 const test = await spot.playlists.getTracks("0vRxeAksQ8ppt6TzxGV7qG");
 console.log(`🚀 ~ loadPodcastInfos ~ test`, test);
```

Expected output:
https://developer.spotify.com/console/get-playlist-tracks/

```
  "items": [
    {
      "added_at": "2022-05-11T19:49:45Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/6xq5zvte0qs0lytr6ccb5wne8"
        },
        "href": "https://api.spotify.com/v1/users/6xq5zvte0qs0lytr6ccb5wne8",
        "id": "6xq5zvte0qs0lytr6ccb5wne8",
        "type": "user",
        "uri": "spotify:user:6xq5zvte0qs0lytr6ccb5wne8"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "compilation",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/show/79CkJF3UJTHFV8Dse3Oy0P"
              },
              "href": "https://api.spotify.com/v1/shows/79CkJF3UJTHFV8Dse3Oy0P",
              "id": "79CkJF3UJTHFV8Dse3Oy0P",
              "name": "Huberman Lab",
              "type": "show",
              "uri": "spotify:show:79CkJF3UJTHFV8Dse3Oy0P"
            }
```

## What actually happened:

![image](https://user-images.githubusercontent.com/48483421/176157154-914f386f-aa30-4811-823e-12f9c4890dd5.png)
track:null

## To reproduce this bug:

- Node Version:  18.3
- Library Version:  9.2.1

- [] I have already checked issues regarding this bug.
- [] This problem is generated due to version migration.

**Comment by scientific-dev** [comment] 2022-07-31 09:47
![image](https://user-images.githubusercontent.com/69678617/182020555-37ce4b9c-e896-48d1-a706-0c1b98579c1c.png)

It works very well. 
And, by the way use the new version of v9.2.2 where it is fixed.

**Comment by scientific-dev** [comment] 2022-11-11 11:33
Closing this as the issue is fixed. If you face further issues, create a new issue.

**Closed by scientific-dev** 2022-11-11 11:33 UTC
Labels: working on
